baseURL = "/"
languageCode = "en-us"
title = "Brave Metaverse"
summaryLength = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.nav]]
    identifier = "about-me"
    name = "Nicholi Noah"
    url = "https://nicholinoah.com"
    weight = 1
  [[menu.nav]]
    identifier = "traditional-media"
    name = "Traditional Media"
    url = "https://nicholinoah.com/traditional-media/"
    weight = 2
  [[menu.nav]]
    identifier = "extended-reality"
    name = "Extended Reality"
    url = "https://nicholinoah.com/extended-reality/"
    weight = 3
  [[menu.nav]]
    identifier = "Brave Metaverse"
    name = "Brave Metaverse"
    url = "/blog/"
    weight = 4